name: nullability
description: Provides handy extension to work with nullable types
version: 1.0.0
repository: https://github.com/FaFre/nullability.git

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
